// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_9tuHDYvJPrA9M7FDXlUep7AXpoKw2o8',
    appId: '1:241934169623:web:a2aa40d3aae81450bece52',
    messagingSenderId: '241934169623',
    projectId: 'noteits',
    authDomain: 'noteits.firebaseapp.com',
    storageBucket: 'noteits.appspot.com',
    measurementId: 'G-27HYTBDCL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH1u9w_s3CftP8Q-Pxeyv_y2DeFdJbFU4',
    appId: '1:241934169623:android:f650440ad4e7a859bece52',
    messagingSenderId: '241934169623',
    projectId: 'noteits',
    storageBucket: 'noteits.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApz7hFIXcjPYXK9SqnaPZerH30pc2U-c4',
    appId: '1:241934169623:ios:ce7b9721bfa0e270bece52',
    messagingSenderId: '241934169623',
    projectId: 'noteits',
    storageBucket: 'noteits.appspot.com',
    iosBundleId: 'com.bkcreations.noteits',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApz7hFIXcjPYXK9SqnaPZerH30pc2U-c4',
    appId: '1:241934169623:ios:ce7b9721bfa0e270bece52',
    messagingSenderId: '241934169623',
    projectId: 'noteits',
    storageBucket: 'noteits.appspot.com',
    iosBundleId: 'com.bkcreations.noteits',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_9tuHDYvJPrA9M7FDXlUep7AXpoKw2o8',
    appId: '1:241934169623:web:7b45c054cf9a2a93bece52',
    messagingSenderId: '241934169623',
    projectId: 'noteits',
    authDomain: 'noteits.firebaseapp.com',
    storageBucket: 'noteits.appspot.com',
    measurementId: 'G-1085Z87D97',
  );

}